---
apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
bootstrapTokens:
- token:
  ttl: "0"
nodeRegistration:
 kubeletExtraArgs:
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.21.0
apiServer:
  extraArgs:
    enable-admission-plugins: NodeRestriction,AlwaysPullImages,DefaultStorageClass
    authorization-mode: Node,RBAC
controllerManager:
  extraArgs:
    allocate-node-cidrs: "true"
    cluster-cidr: 10.0.0.0/16
    enable-taint-manager: "false"
networking:
  serviceSubnet: 10.49.0.0/16
  podSubnet: 10.48.0.0/16
  dnsDomain: cluster.local
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: iptables
---
